### ISSUE TITLE
GUI Error: You are pushing more GUIClips than you are pooping.

### ISSUE THREAD

**Issue by Jeceratops** [ChrisAdderley/Waterfall#12]
Getting a weird error in a testing RSS RO save "GUI Error: You are pushing more GUIClips than you are pooping. Make sure they are balanced" No crash but it is causing quite a bit of log spam. The log spam only starts after trying to edit the plume of an engine. Il try updating my version of waterfall (pre engine sounds) 

![image](https://user-images.githubusercontent.com/69649180/90350294-a6be3700-e00a-11ea-80c7-2720d7b98279.png)
[ERR 21:44:31.712] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.

[EXC 21:44:31.714] ArgumentException: GUILayout: Mismatched LayoutGroup.repaint
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	Waterfall.UI.WaterfallUI.DrawHeader () (at <0999e3071be647559608c59c265f4138>:0)
	Waterfall.UI.WaterfallUI.DrawWindow (System.Int32 windowId) (at <0999e3071be647559608c59c265f4138>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <fa6f9762ac624af092525d37c9d516c4>:0)
[EXC 21:44:31.728] NullReferenceException: Object reference not set to an instance of an object
	Waterfall.EffectModifier.Apply (System.Collections.Generic.List`1[T] strength) (at <0999e3071be647559608c59c265f4138>:0)
	Waterfall.WaterfallEffect.Update () (at <0999e3071be647559608c59c265f4138>:0)
	Waterfall.ModuleWaterfallFX.LateUpdate () (at <0999e3071be647559608c59c265f4138>:0)
[EXC 21:44:31.796] NullReferenceException: Object reference not set to an instance of an object
	Waterfall.WaterfallEffect.SetEnabled (System.Boolean state) (at <0999e3071be647559608c59c265f4138>:0)
	Waterfall.UI.UIEffectWidget.Draw () (at <0999e3071be647559608c59c265f4138>:0)
	Waterfall.UI.WaterfallUI.DrawEffectsList () (at <0999e3071be647559608c59c265f4138>:0)
	Waterfall.UI.WaterfallUI.DrawWindow (System.Int32 windowId) (at <0999e3071be647559608c59c265f4138>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <fa6f9762ac624af092525d37c9d516c4>:0)
![image](https://user-images.githubusercontent.com/69649180/90350294-a6be3700-e00a-11ea-80c7-2720d7b98279.png)

**Comment by ChrisAdderley** [comment]
That usually means something was broken earlier in the log. This is why it is essential to post full logs.

**Comment by Jeceratops** [comment]
Ok, can do, I don't have access to my PC for awhile, I'll send them here once I can. Do you need the Ksp logs or the .player?

**Comment by Jeceratops** [comment]
Fixed with a change of parentName
